= Workspace

This repository encapsulates some shell scripts and a VS Code workspace config to install and manage all my personal code repositories.

== Requirements

https://git-lfs.com/[Git LFS] MUST be installed before cloning the repositories. It is RECOMMENDED to clone and run the environment https://github.com/kieranpotts/bootstrap[bootstrapping script], before installing all the other repositories.

== Usage

NOTE: On Windows, the workspace SHOULD be established in WSL. The `devtools` repository SHOULD also be cloned directly in the host OS, manually, and optionally the `dotfiles` repository too.

[source,sh]
----
# Clone all repositories.
bash ./run/install.sh

# Synchronize the main branches of all local repositories with their
# tracked upstream branches.
bash ./run/sync.sh
----

The repositories will be cloned adjacent to the `workspace` repository. The parent directory will be the workspace root in VS Code.

[source,sh]
----
# Create a symlink from the VS Code workspace configuration to the
# workspace root directory.
ln -s -f ./etc/personal.code-workspace /path/to/workspace/personal.code-workspace
----

Change directory to the workspace root, then open the symlinked workspace configuration from that location.

[source,sh]
----
# Open the VS Code workspace.
cd /path/to/workspace
code personal.code-workspace
----

''''

Copyright © 2020-present Kieran Potts, all rights reserved.
